(clear)
(load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/0_Main.clp)
(load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/1_Game.clp)
(load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/2_Code.clp)
(load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/3_Agent.clp)
:: (load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/4_Dumb_computer.clp)
(load C:/Users/marco/OneDrive/Desktop/IALAB/IALAB-1/CLIPS/master-mind/6_test.clp)
(reset)
